baseURL = 'https://bojan.delic.rs/'
languageCode = 'en-us'
title = 'Bojan Delić'
theme = 'minimal'

[params]
  tagline = 'Problem solver, computer programmer, IT enthusiast, geek'
  description = 'Personal website of Bojan Delić'
  email = 'bojan@delic.in.rs'
  github = 'https://github.com/delicb'
  linkedin = 'https://www.linkedin.com/in/bojandelic/'
  twitter = 'https://x.com/dercibald'
  twitterHandle = '@dercibald'
#iturnstileSiteKey = '1x00000000000000000000AA' # Test key for local development
  turnstileSiteKey = '0x4AAAAAACbCN_Yiit6Tonql'

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = false
    lineNumbersInTable = true
    anchorLineNos = true
    codeFences = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  [permalinks.page]
    blog = '/blog/:year/:month/:slug/'

[pagination]
  pagerSize = 10

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML', 'RSS']

[sitemap]
  changeFreq = 'weekly'
  filename = 'sitemap.xml'
